export const SCENARIOS = [
  {
    code: 'TEST_TIMEOUT',
    title: 'Test Timeout',
    summary: 'Long-running flow that exceeds typical test timeouts.',
    developerMeaning: 'The test exceeded its overall timeout before the flow completed.',
    likelyCauses: ['Long-running async work', 'Unbounded waits', 'Excessive network or UI delays'],
    suggestedFixes: ['Shorten the flow', 'Mock slow steps', 'Increase test timeout only if justified'],
    reproHint: 'Start the flow and wait for completion beyond normal timeouts.',
    severity: 'High',
    defaultMode: 'long-load',
    supportedModes: ['long-load'],
    supportsDuration: true,
    defaultDurationMs: 38000,
    supportsAutoStart: true
  },
  {
    code: 'ASSERT_TIMEOUT',
    title: 'Assert Timeout',
    summary: 'A status label never reaches the expected value.',
    developerMeaning: 'An expectation waited too long for a UI state change.',
    likelyCauses: ['State never updates', 'Wrong selector', 'Async work never finishes'],
    suggestedFixes: ['Check state transitions', 'Validate locator', 'Fix missing state updates'],
    reproHint: 'Observe a label that stays on the wrong value or resolves slowly.',
    severity: 'Medium',
    defaultMode: 'never-resolve',
    supportedModes: ['never-resolve', 'slow-success'],
    supportsDuration: true,
    defaultDurationMs: 20000
  },
  {
    code: 'ACTION_TIMEOUT',
    title: 'Action Timeout',
    summary: 'A visible control never becomes actionable.',
    developerMeaning: 'An action (click/type) could not be completed in time.',
    likelyCauses: ['Overlay blocking', 'Disabled button', 'Prerequisite never met'],
    suggestedFixes: ['Wait for actionable state', 'Remove blockers', 'Ensure prerequisites can complete'],
    reproHint: 'Attempt to click the target control while it stays blocked.',
    severity: 'High',
    defaultMode: 'blocked-overlay',
    supportedModes: ['blocked-overlay', 'waiting-on-fake-prerequisite', 'disabled-forever']
  },
  {
    code: 'ELEMENT_NOT_VISIBLE',
    title: 'Element Not Visible',
    summary: 'The target exists in DOM but is hidden.',
    developerMeaning: 'A locator matched an element that is not visible on screen.',
    likelyCauses: ['CSS display/visibility', 'Collapsed containers', 'Hidden tabs'],
    suggestedFixes: ['Wait for visibility', 'Switch to correct tab', 'Fix layout'],
    reproHint: 'Try to interact with the hidden target.',
    severity: 'Medium',
    defaultMode: 'display-none',
    supportedModes: ['display-none', 'collapsed', 'hidden-tab']
  },
  {
    code: 'ELEMENT_NOT_STABLE',
    title: 'Element Not Stable',
    summary: 'A moving target remains unstable for several seconds.',
    developerMeaning: 'The element keeps moving or animating during interaction.',
    likelyCauses: ['Animations still running', 'Layout shifts', 'Transitions'],
    suggestedFixes: ['Wait for stability', 'Disable animations in tests'],
    reproHint: 'Try to click the moving target while it animates.',
    severity: 'Medium',
    defaultMode: 'continuous',
    supportedModes: ['continuous', 'stops-after'],
    supportsDuration: true,
    defaultDurationMs: 6000
  },
  {
    code: 'ELEMENT_OBSCURED',
    title: 'Element Obscured',
    summary: 'The target is visible but covered by another element.',
    developerMeaning: 'Click is intercepted by an overlay or blocking element.',
    likelyCauses: ['Modal overlays', 'Sticky banners', 'Toasts'],
    suggestedFixes: ['Wait for overlay removal', 'Close blockers', 'Use force click only if safe'],
    reproHint: 'Attempt to click the covered target.',
    severity: 'High',
    defaultMode: 'full-overlay',
    supportedModes: ['full-overlay', 'toast-overlap', 'banner-overlap']
  },
  {
    code: 'ELEMENT_DISABLED',
    title: 'Element Disabled',
    summary: 'A disabled control never enables, or enables late.',
    developerMeaning: 'The element is present but not enabled for interaction.',
    likelyCauses: ['Prerequisite state missing', 'Validation fails', 'Feature flags'],
    suggestedFixes: ['Trigger prerequisite', 'Fix validation logic'],
    reproHint: 'Try to click a disabled button that remains disabled.',
    severity: 'Medium',
    defaultMode: 'delayed-enable',
    supportedModes: ['delayed-enable', 'never-enable'],
    supportsDuration: true,
    defaultDurationMs: 5000
  },
  {
    code: 'LOCATOR_NOT_FOUND',
    title: 'Locator Not Found',
    summary: 'The expected element never appears in the DOM.',
    developerMeaning: 'A locator could not find any matching elements.',
    likelyCauses: ['Conditional rendering', 'Delayed load', 'Filtering'],
    suggestedFixes: ['Wait for render', 'Fix rendering conditions', 'Check selectors'],
    reproHint: 'Look for a target that never mounts.',
    severity: 'High',
    defaultMode: 'not-mounted',
    supportedModes: ['not-mounted', 'delayed-mount', 'filtered-away'],
    supportsDuration: true,
    defaultDurationMs: 15000
  },
  {
    code: 'LOCATOR_MULTIPLE_MATCHES',
    title: 'Locator Multiple Matches',
    summary: 'Multiple elements match the same locator.',
    developerMeaning: 'A locator is ambiguous and returns more than one match.',
    likelyCauses: ['Duplicate accessible names', 'Repeating controls', 'Missing unique attributes'],
    suggestedFixes: ['Use more specific locators', 'Add unique identifiers'],
    reproHint: 'Target an element with duplicate accessible names.',
    severity: 'Medium',
    defaultMode: 'duplicate-buttons',
    supportedModes: ['duplicate-buttons', 'duplicate-links', 'duplicate-inputs']
  },
  {
    code: 'STALE_DOM_REFERENCE',
    title: 'Stale DOM Reference',
    summary: 'The element is replaced in the DOM after interaction.',
    developerMeaning: 'A previously located element is detached and replaced.',
    likelyCauses: ['React re-renders', 'Key changes', 'Route transitions'],
    suggestedFixes: ['Re-locate before interacting', 'Wait for stable DOM'],
    reproHint: 'Observe a target that remounts after a short delay.',
    severity: 'Medium',
    defaultMode: 'auto-remount',
    supportedModes: ['auto-remount', 'on-interaction'],
    supportsDuration: true,
    defaultDurationMs: 2500
  },
  {
    code: 'NAVIGATION_TIMEOUT',
    title: 'Navigation Timeout',
    summary: 'A route-like view never finishes loading.',
    developerMeaning: 'Navigation or content transition did not complete.',
    likelyCauses: ['Loading shell stuck', 'Promise never resolves', 'Broken navigation'],
    suggestedFixes: ['Wait for navigation', 'Fix data loading', 'Handle errors'],
    reproHint: 'Trigger an internal navigation that never finishes.',
    severity: 'High',
    defaultMode: 'infinite-loading-shell',
    supportedModes: ['infinite-loading-shell', 'delayed-content', 'unresolved-content-pane'],
    supportsDuration: true,
    defaultDurationMs: 12000
  },
  {
    code: 'NETWORK_REQUEST_FAILED',
    title: 'Network Request Failed',
    summary: 'A fake request fails, times out, or is aborted.',
    developerMeaning: 'A network call did not succeed or timed out.',
    likelyCauses: ['Server error', 'Network issues', 'Request cancellation'],
    suggestedFixes: ['Retry logic', 'Handle failure states', 'Add timeouts'],
    reproHint: 'Run a fake request with a deterministic outcome.',
    severity: 'High',
    defaultMode: 'success',
    supportedModes: ['success', 'timeout', 'aborted', 'network-failure'],
    supportsDuration: true,
    defaultDurationMs: 10000,
    supportsAutoStart: true
  },
  {
    code: 'PAGE_CLOSED',
    title: 'Page Closed',
    summary: 'A popup closes quickly or a target disappears.',
    developerMeaning: 'The page or context closes before an action completes.',
    likelyCauses: ['Popup blocked/closed', 'Navigation interrupts flow', 'Window closed'],
    suggestedFixes: ['Wait for popup', 'Handle close events'],
    reproHint: 'Open a child window that closes immediately.',
    severity: 'Medium',
    defaultMode: 'auto-close-window',
    supportedModes: ['auto-close-window', 'vanishing-region'],
    supportsDuration: true,
    defaultDurationMs: 800
  },
  {
    code: 'APP_RUNTIME_ERROR',
    title: 'App Runtime Error',
    summary: 'A component throws at runtime.',
    developerMeaning: 'A runtime error interrupts normal rendering or interaction.',
    likelyCauses: ['Unhandled exceptions', 'Null dereference', 'Async failures'],
    suggestedFixes: ['Add guards', 'Use error boundaries', 'Fix data assumptions'],
    reproHint: 'Trigger a component that throws on mount or click.',
    severity: 'Critical',
    defaultMode: 'throw-on-mount',
    supportedModes: ['throw-on-mount', 'throw-on-click', 'throw-on-async'],
    supportsDuration: true,
    defaultDurationMs: 1500
  }
];

export const getScenarioByCode = (code) => {
  if (!code) return null;
  return SCENARIOS.find((scenario) => scenario.code === code.toUpperCase()) || null;
};
